services:
  # Backend API Service
  - type: web
    name: course-builder-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 10000
    healthCheckPath: /health

  # Frontend Static Site
  - type: web
    name: course-builder-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: VITE_API_URL
        value: https://course-builder-api.onrender.com

# Database - SQLite будет в памяти, для продакшн рекомендуется PostgreSQL

