services:
  # Backend API Service
  - type: web
    name: course-builder-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 10000
    healthCheckPath: /health

# Database - SQLite будет в памяти, для продакшн рекомендуется PostgreSQL
# 
# ВАЖНО: Frontend нужно создать вручную как Static Site через Dashboard
# См. инструкцию в DEPLOY.md или RENDER_QUICKSTART.md

